### ISSUE TITLE
Spyware?

### ISSUE THREAD

**Issue by DJ-Demon** [bewue/WLANScanner#1]
The latest version 1.1.0 requires access to my location data, otherwise it doesn't work Why? Did you turn WLANScanner into spyware?

**Comment by bewue** [comment]
WLANScanner is only processing data to show you the WiFi scan results.
Since Android 8.0 there are new permission requirements to get these scan results.
https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-permissions

**Comment by DJ-Demon** [comment]
Pardon me, but I doubt that this is correct.

I have been using the previous version of WLANScanner succcessfully with Android **8.1** until  yesterday, when I updated WLANScanner. After starting it, a window popped up, saying "The app requires all requested permissions to work properly".  I checked the Android settings regarding the permissions of the app, and the access to the location data was shown as **off**.

This means that the previous version was running perfectly on Android 8.1 **without** having been granted permission to know my location.

**Comment by bewue** [comment]
On my Android 8.0 device i get no scan results if the location permission is not granted.
In fact theres no mechanism in the app code to block the scan results if the permission is not granted,
thats handled by the android system!

WLANScanner is not spyware! The source code is available to everyone and a download via F-Droid is also available.
