### ISSUE TITLE
Full of Deprecated API's

### ISSUE THREAD

**Issue by rydersan** [bewue/WLANScanner#12]
This app has full of deprecated API's. Sadly.
Example is Actionbar and Tab view. My Android Studio shows as deprecated code and app can`t be lauched.

**Comment by rydersan** [comment]
> This app has full of deprecated API's. Sadly. Example is Actionbar and Tab view. My Android Studio shows as deprecated code and app can`t be lauched.

I`m working on it to Update by myself with modern API's. :))
But code presented by project author... much respect, but ain't working. While debugging deprecated code lines appears and that means project can't be launched.

**Comment by bewue** [comment]
I have had no problems opening the project in android studio. With more information I may be able to help you.

Yes, there are some older Android UI APIs used, I haven't found time to migrate the whole thing to current UI APIs yet. But using older APIs shouldn't be a drama either! If you are working on it you should also pay attention to the support on older Android versions...

It's always helpful to have capable people like you helping out with open source projects, not just talking big ;)

**Comment by rydersan** [comment]
Hm, interesting.
Questions. Which Android Studio version you have while building this
project? And also which gradle version do you use while building this
project?

Thanks!

**Comment by bewue** [comment]
I tried the current stable stuff, ...it works for me:
- Android Studio Giraffe | 2022.3.1 Patch 2
- Android Gradle Plugin 8.1.2
-  Gradle 8.0, also tested with Gradle 8.4

**Comment by rydersan** [comment]
Hm, interesting!
For me it didn’t worked. I Also have current versions AS and it components.
Ok! Within 12 hours I will try to open project again and make sure that AS
and gradles packages are same as yours , although I think they are.

Ty

**Comment by rydersan** [comment]
I finnaly got it running.
Yeah. The problem was gradle plugin version, but Not AS (Android Studio).
AS , it was already the latest One.

Alright. I may beging upgrading your (if it’s yours) project to most
advanced including front-end and back-end programming.
