### ISSUE TITLE
The application does not see Wi-Fi networks

### ISSUE THREAD

**Issue by Korb** [bewue/WLANScanner#13]
![Screenshot_20231218_165838](https://github.com/bewue/WLANScanner/assets/3509797/999b8c78-49e9-40d3-9740-22da4431dfe9)
![Screenshot_20231218_165833](https://github.com/bewue/WLANScanner/assets/3509797/fc4bfdd0-6535-4744-b20b-a3937f633a37)

WLANScanner 1.3.2 f-droid

OS version: Funtouch OS 13 Global
Model: Vivo T1 (4G) / V2153
Hardware version: MP_0.1
Build number: PD22010F_EX_A_13.1.16.2. W20. V000L1
Baseband version: MPSS.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.130
Kernel version: 4.19.157-perf+, 1 Wed Nov 1 16:53:10 CST 2023
Compile time: 1 Nov 2023 11:55:18
Android security update: 1 November 2023
Google Play system update: 1 October 2023

**Comment by bewue** [comment]
I also have Android 13 on my Phone and it works.

You could check 2 things:
1. WiFi is turned on on the device
2. [Location Services are enabled](https://github.com/bewue/WLANScanner#important-note)

**Comment by Korb** [comment]
> To get scan results the following requirements must be met: the app has the permission to query the location services the location services on the device are enabled (Settings > Location) Information about the required permissions If your system supports it, you can grant the permissions in the next step.

Most likely, the issue was indeed a disabled location service. I suggest adding a check to the application that this service is enabled and, if it is disabled, giving the user a warning that the application cannot work without it.

**Comment by bewue** [comment]
When the app is started for the first time, a pop-up appears indicating that the location services must be enabled. But you are right, if you try to scan and the location services are disabled, it would make sense to display a note.

**Comment by bewue** [comment]
#14
