### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [bewue/WLANScanner#2]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by bewue** [comment]
In this repo i provide the fastlane structure. I hope it will be parsed with the next "fdroid app build" within the next days.

**Comment by mondlicht-und-sterne** [comment]
Yes, that is exactly what needs to be entered in fastlane.
