### ISSUE TITLE
Offset in 2.4GHz channel number ?

### ISSUE THREAD

**Issue by CRprog** [bewue/WLANScanner#3]
Hi,
I'am using a Samsung A41 and I discovered a strange offset in the displayoutput (List- and 2.4GHz tab) of the channel number:
Fritzbox fixed set to Ch3   -> WLAN-Scanner shows Ch5
Fritzbox fixed set to Ch11 -> WLAN-Scanner shows Ch9 

An also to fritzbox connected repeater (of course, according to the same fixed set channel)
is also found in the WLANScanner-list with the wrong channel.

Complete representation (List) for Fritzbox Ch11:
MyAPname         -58dBm
WPA2-PSK-CCMP RSN-PSK-CCMP WPA-PSK-TKIP ESS
2.4GHz  40MHz   [9]   00:1f:3f:a4:xx:xx

Any idea whats going wrong ?

Regards.

**Comment by bewue** [comment]
The app should show you the channel number of the center frequency of the channel.
If you compare the results of the diagram view with other scanners then there should be no differences.

But I have also noticed that other scanners give 2 numbers for the channel description,  i haven't found out yet what it's all about and if it makes sense ;)

**Comment by CRprog** [comment]
I left the Fritzbox fixed on channel 11 with checked Option "Use radio channels optimized for 300 Mbit/s" -> 40 MHZ bandwith 
The "WiFiAnalyzer" (from vremsoftwaredevelopment) draws a comparable graphic (center at Ch9) to your program. 
But it lists the access points (as you mentioned above) as follows: 
-62 dBm CH 11(9) 2462MHz
2432 - 2472 (40MHz)

An accesspoint from the neighborhood with only 20MHz bandwith on Ch13 for comparison: (graphic center at Ch13)
-76 dBm CH 13 2472MHz
2462 - 2482 (20MHz)

Maybe the two numbers at 40 MHz bandwidth make sense, I don't really understand it right now either.
Conclusion: 
Everything ok with your software, 40MHz is something special, maybe later on you will just print out two numbers also. 

I'll close this issue in a few days ...

**Comment by LordCozyCat** [comment]
> I left the Fritzbox fixeon channel 11 with checked Option "Use radio channels optimized for 300 Mbit/s" -> 40 MHZ bandwith
> The "WiFiAnalyzer" (from vremsoftwaredevelopment) draws a comparable graphic (center at Ch9) to your program.
> But it lists the access points (as you mentioned above) as follows:
> -62 dBm CH 11(9) 2462MHz
> 2432 - 2472 (40MHz)
> 
> An accesspoint from the neighborhood with only 20MHz bandwith on Ch13 for comparison: (graphic center at Ch13)
> -76 dBm CH 13 2472MHz
> 2462 - 2482 (20MHz)
> 
> Maybe the two numbers at 40 MHz bandwidth make sense, I don't really understand it right now either.
> Conclusion:
> Everything ok with your software, 40MHz is something special, maybe later on you will just print out two numbers also.
> 
> I'll close this issue in a few days ...

When using 2.4GHz with a 40MHz channel width you're bonding two channels together. If you select channel 11, it bonds channel 11 with channel 7 to create 40MHz of width, making the center of this width channel 9. WLANScanner shows the center frequency.

Ubiquiti's WifiMan shows the set channel (in your case it show channel 11, but the graph would have channel 9 in the center.

The WiFiAnalyzer app you mention seems to be displaying the channel set by the Access Point just like WiFiMan, and then the center of the channel bond in parentheses.

I've seen other WiFi analyzers show the two bonded channels, so it would display Channel 7, Channel 11.

**Comment by CRprog** [comment]
Thank you for your explanations.
