### ISSUE TITLE
Need more docs on why precise location permission is necessary

### ISSUE THREAD

**Issue by jrcjohn** [bewue/WLANScanner#5]
Downloading a non-navigation app in F-Droid that doesn't work without GPS enabled is a red flag.

Explain in a popup why WifiScanner cannot read SSIDs / channels / signal strength without GPS to justify this requirement.

**Comment by totoroot** [comment]
Under the [Important Note](https://github.com/bewue/WLANScanner#important-note) section in the README there is a [link](https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-restrictions) that leads to the following section in the Android developer documentation that says:

> Android 8.0 (API level 26) introduced restrictions regarding permissions and the allowed frequency of Wi-Fi scans.
>
>To improve network performance, security, and battery life, Android 9 (API level 28) tightened permission requirements and further limited the frequency of Wi-Fi scans.

@jrcjohn, do you feel like mentioning the official Android developer documentation is not clear enough?

**Comment by bewue** [comment]
The next release (v1.3.0) will include a modified permission info popup with more information. 62523ad99f7489e28979f6c6e2e2ad7f43e69979 ff296b5da97bda609d40c66c335fa83e052d4a98

![permissions-info](https://user-images.githubusercontent.com/38508611/219135011-6075080b-0bd3-410f-99a2-5d4b2543d7f7.png)

**Comment by bewue** [comment]
closing.
