### ISSUE TITLE
[Feature Request] Filter Option to Exclude

### ISSUE THREAD

**Issue by ForrestHerman** [bewue/WLANScanner#6]
Would it be possible to update the functionality of the filter options to exclude the specified items rather than only display the selected items? 

I'm currently working in an area that has a couple of dozen APs visible to my phone for the main network (all with the same SSID) and for what I am doing, being able to filter all of those out and view only the remaining items would be very useful.

**Comment by bewue** [comment]
The next release (v1.3.0) will contain a filter "Invert-Match" option. ef1c3a26d3ea349c338bf87946d53ecc30343353

![filter-popup](https://user-images.githubusercontent.com/38508611/219136576-431ad369-be55-4d0f-a79b-5bdb722f3372.png)
