### ISSUE TITLE
5 GHz channel numbers are incorrect

### ISSUE THREAD

**Issue by MarkWieczorek** [bewue/WLANScanner#7]
On my router, I chose to use channel number 100 on 5GHz (80 MHz width). My computer confirms that I am connected to channel 100. However, when I use WLANscanner, it says that I am connected to channel 106. I note that the wifi channel of my 2.4 GHz network is correct.

Version 1.2.0
Samsung S9
/e/OS 1.1

**Comment by bewue** [comment]
Channel number 106 is the channel of the center frequency that will be used in that range and with 80 MHz width. You can verify that [here](https://en.wikipedia.org/wiki/List_of_WLAN_channels). To show the center channel is useful and technically correct in my opinion. I don't know why also some big vendors don't realize that ;)

**Comment by MarkWieczorek** [comment]
Well, that is bizarre. I Just assumed that the channel was always for the central frequency...
