### ISSUE TITLE
6 GHz scanning not working on S22 Ultra

### ISSUE THREAD

**Issue by poisonnuke** [bewue/WLANScanner#8]
Hi,

On my S22u in a joined 6E network its not possible to see the channel (53, psc) in the app. 5GHz and 2.4 is working fine.

![Screenshot_20221018-145746_WLANScanner](https://user-images.githubusercontent.com/9219451/196537986-3071e092-2757-473c-b5aa-fad1d6ad03d2.jpg)

![Screenshot_20221018-223344_Settings](https://user-images.githubusercontent.com/9219451/196538236-d74a49e1-f05f-4f59-b7a2-1fcd49c0fc33.jpg)

Can I help in any way to investigate that issue?

**Comment by bewue** [comment]
Can you find the network in the list view?
Remember that you may have to wait up to a minute for a new scan to take place.

Other things you can try one by one to find the cause:
1. Disconnect from network
2. Disable PSC on the router (i dont think thats possible on the phone)

**Comment by poisonnuke** [comment]
> Can you find the network in the list view? Remember that you may have to wait up to a minute for a new scan to take place.

after waiting a while it did pop up in the list, indeed. But even after 10 minutes, nothing in the channel-graph. Which is the feature Im using the app for in the first place.

> Other things you can try one by one to find the cause:
> 
> 1. Disconnect from network

nope, did not help

> 2. Disable PSC on the router (i dont think thats possible on the phone)

PSC is nothing you can disable, its a fundamental concept of 6GHz channels. And if so, then the phone must supply that option, because the phone is doing the scanning, not the router. But PSC is part of the standard and its not meant to be disabled (because a client would need roughly 6 minutes for all 229 channels to scan)

**Comment by bewue** [comment]
After a longer break I can now work on the app again.

Unfortunately, I don't currently have a 6 GHz capable device.
So I'm a bit dependent on you for troubleshooting.

Which values are displayed for the 6 GHz WLAN in the list view? It would be interesting if the frequency band (6 GHz, 5 GHz, 2.4 GHz) and channel (e.g. 53) is displayed correctly.

Do you have the possibility to see the logs of your Android device?
If you want to do that you will find instructions on the internet. Maybe then errors in the logs are visible.

Also, I will soon release a new version of the app built with a more recent Android SDK, so maybe that will solve your problem.

**Comment by poisonnuke** [comment]
Hello sorry, I had some reconfigurations with WiFi 6E and learned a few lessons my self (for example you need to send beacons on 2.4 or 5ghz in order to see SSIDs in 6GHz in the first place, but thats something that the WiFi driver should take care of.

nevertheless, here is a list view of the wifi, as you can see, all SSIDs are listed, including all 6E. But no channel and no Ghz, just question-marks. 

I can look into the log but please specify what I should look for, you should know the length of the log is unfathomable even in a second there are hundreds of entries.
![Screenshot_20230718_105506_WLANScanner](https://github.com/bewue/WLANScanner/assets/9219451/4281b84a-e852-4f68-9a03-a77c871cf58f)

**Comment by bewue** [comment]
I cant see your screenshot. Please try upload again.
You can try to filter the log for the tag "wlanscanner" or just the string "wlanscanner". Then additionally filter for warnings or errors, this could lead to the cause.

**Comment by poisonnuke** [comment]
[debug.log](https://github.com/bewue/WLANScanner/files/12143621/debug.log)
Hi, here is the grep from logcat, and the screenshot is also attached now in above posting

**Comment by bewue** [comment]
I think the list of 6 GHz channel numbers/frequencies in the app was wrong.
It might be fixed now in e055c09. You can try the new apk: [v1.3.2](https://github.com/bewue/WLANScanner/releases/tag/v1.3.2)

**Comment by poisonnuke** [comment]
it is working like a charm now

**Comment by poisonnuke** [comment]
closed
